# Generated by Django 5.0.7 on 2024-07-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='is_public',
            field=models.BooleanField(verbose_name='признак публичности'),
        ),
    ]
