# Generated by Django 5.0.7 on 2024-07-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_section_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='признак публичности'),
        ),
    ]
